from k.core import Cantatio

import k.util.text

TIRONIAN = {
    "noun or verb acting prenominally"                                        : "n., v. acting prenominally",
    "adjective (keiyoushi)"                                                   : "adj.",
    "adjective (keiyoushi) - yoi/ii class"                                    : "adj., 'yoi/ii'",
    "'kari' adjective (archaic)"                                              : "arch. adj., 'kari'",
    "'ku' adjective (archaic)"                                                : "arch. adj., 'ku'",
    "adjectival nouns or quasi-adjectives (keiyodoshi)"                       : "adjl. n. or quasi-adj.",
    "archaic/formal form of na-adjective"                                     : "arch. or formal of na-adj.",
    "nouns which may take the genitive case particle 'no'"                    : "n. prob. with gen. part., 'no'",
    "pre-noun adjectival (rentaishi)"                                         : "pre-n. adjl.",
    "'shiku' adjective (archaic)"                                             : "arch. adj., 'shiku'",
    "'taru' adjective"                                                        : "adj., 'taru'",
    "adverb (fukushi)"                                                        : "adv.",
    "adverb taking the 'to' particle"                                         : "adv. taking part., 'to'",
    "auxiliary"                                                               : "aux.",
    "auxiliary adjective"                                                     : "aux. adj.",
    "auxiliary verb"                                                          : "aux. v.",
    "conjunction"                                                             : "conj.",
    "copula"                                                                  : "cop.",
    "counter"                                                                 : "count.",
    "expressions (phrases, clauses, etc.)"                                    : "expr.",
    "interjection (kandoushi)"                                                : "interj.",
    "noun (common) (futsuumeishi)"                                            : "n.",
    "adverbial noun (fukushitekimeishi)"                                      : "n. advl.",
    "proper noun"                                                             : "n. prop.",
    "noun, used as a prefix"                                                  : "n. pref.",
    "noun, used as a suffix"                                                  : "n. suff.",
    "noun (temporal) (jisoumeishi)"                                           : "n. temp.",
    "numeric"                                                                 : "num.",
    "pronoun"                                                                 : "pron.",
    "prefix"                                                                  : "prefix",
    "particle"                                                                : "part.",
    "suffix"                                                                  : "suffix",
    "unclassified"                                                            : "unkn.",
    "verb unspecified"                                                        : "v.",
    "Ichidan verb"                                                            : "v. ichidan",
    "Ichidan verb - kureru special class"                                     : "v. ichidan [!]",
    "Nidan verb with 'u' ending (archaic)"                                    : "arch. v. nidan ↑ -u",
    "Nidan verb (upper class) with 'bu' ending (archaic)"                     : "arch. v. nidan ↑ -bu",
    "Nidan verb (lower class) with 'bu' ending (archaic)"                     : "arch. v. nidan ↓ -bu",
    "Nidan verb (upper class) with 'dzu' ending (archaic)"                    : "arch. v. nidan ↑ -dzu",
    "Nidan verb (lower class) with 'dzu' ending (archaic)"                    : "arch. v. nidan ↓ -dzu",
    "Nidan verb (upper class) with 'gu' ending (archaic)"                     : "arch. v. nidan ↑ -gu",
    "Nidan verb (lower class) with 'gu' ending (archaic)"                     : "arch. v. nidan ↓ -gu",
    "Nidan verb (upper class) with 'hu/fu' ending (archaic)"                  : "arch. v. nidan ↑ -hu, -fu",
    "Nidan verb (lower class) with 'hu/fu' ending (archaic)"                  : "arch. v. nidan ↓ -hu, -fu",
    "Nidan verb (upper class) with 'ku' ending (archaic)"                     : "arch. v. nidan ↑ -ku",
    "Nidan verb (lower class) with 'ku' ending (archaic)"                     : "arch. v. nidan ↓ -ku",
    "Nidan verb (upper class) with 'mu' ending (archaic)"                     : "arch. v. nidan ↑ -mu",
    "Nidan verb (lower class) with 'mu' ending (archaic)"                     : "arch. v. nidan ↓ -mu",
    "Nidan verb (lower class) with 'nu' ending (archaic)"                     : "arch. v. nidan ↓ -nu",
    "Nidan verb (upper class) with 'ru' ending (archaic)"                     : "arch. v. nidan ↑ -ru",
    "Nidan verb (lower class) with 'ru' ending (archaic)"                     : "arch. v. nidan ↓ -ru",
    "Nidan verb (lower class) with 'su' ending (archaic)"                     : "arch. v. nidan ↓ -su",
    "Nidan verb (upper class) with 'tsu' ending (archaic)"                    : "arch. v. nidan ↑ -tsu",
    "Nidan verb (lower class) with 'tsu' ending (archaic)"                    : "arch. v. nidan ↓ -tsu",
    "Nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)" : "arch. v. nidan ↓ -u & 'we' conj.",
    "Nidan verb (upper class) with 'yu' ending (archaic)"                     : "arch. v. nidan ↑ -yu",
    "Nidan verb (lower class) with 'yu' ending (archaic)"                     : "arch. v. nidan ↓ -yu",
    "Nidan verb (lower class) with 'zu' ending (archaic)"                     : "arch. v. nidan ↓ -zu",
    "Yodan verb with 'bu' ending (archaic)"                                   : "arch. v. yodan -bu",
    "Yodan verb with 'gu' ending (archaic)"                                   : "arch. v. yodan -gu",
    "Yodan verb with 'hu/fu' ending (archaic)"                                : "arch. v. yodan -hu, -fu",
    "Yodan verb with 'ku' ending (archaic)"                                   : "arch. v. yodan -ku",
    "Yodan verb with 'mu' ending (archaic)"                                   : "arch. v. yodan -mu",
    "Yodan verb with 'nu' ending (archaic)"                                   : "arch. v. yodan -nu",
    "Yodan verb with 'ru' ending (archaic)"                                   : "arch. v. yodan -ru",
    "Yodan verb with 'su' ending (archaic)"                                   : "arch. v. yodan -su",
    "Yodan verb with 'tsu' ending (archaic)"                                  : "arch. v. yodan -tsu",
    "Godan verb - -aru special class"                                         : "v. godan -aru [!]",
    "Godan verb with 'bu' ending"                                             : "v. godan -bu",
    "Godan verb with 'gu' ending"                                             : "v. godan -gu",
    "Godan verb with 'ku' ending"                                             : "v. godan -ku",
    "Godan verb - Iku/Yuku special class"                                     : "v. godan iku, yuku [!]",
    "Godan verb with 'mu' ending"                                             : "v. godan -mu",
    "Godan verb with 'nu' ending"                                             : "v. godan -nu",
    "Godan verb with 'ru' ending"                                             : "v. godan -ru",
    "Godan verb with 'ru' ending (irregular verb)"                            : "v. godan -ru (irreg.)",
    "Godan verb with 'su' ending"                                             : "v. godan -su",
    "Godan verb with 'tsu' ending"                                            : "v. godan -tsu",
    "Godan verb with 'u' ending"                                              : "v. godan -u",
    "Godan verb with 'u' ending (special class)"                              : "v. godan -u [!]",
    "Godan verb - Uru old class verb (old form of Eru)"                       : "v. godan, obs. uru (obs. of eru)",
    "intransitive verb"                                                       : "v.i.",
    "Kuru verb - special class"                                               : "v., kuru [!]",
    "irregular nu verb"                                                       : "v. irreg., nu",
    "irregular ru verb, plain form ends with -ri"                             : "v. irreg., ru (-ri plain end)",
    "noun or participle which takes the aux. verb suru"                       : "n. or ptcp. taking aux. v., suru",
    "su verb - precursor to the modern suru"                                  : "v., su, origo suru",
    "suru verb - included"                                                    : "v., suru, incl.",
    "suru verb - special class"                                               : "v., suru [!]",
    "transitive verb"                                                         : "v.t.",
    "Ichidan verb - zuru verb (alternative form of -jiru verbs)"              : "v. ichidan, zuru v. (alt. -jiru)",
}

class Pass(Cantatio):
    def do(self, entry, _):
        for _, sense in entry["senses"]:
            if "poss" in sense:
                poss = []
                for pos in sense["poss"]:
                    try:
                        poss.append(TIRONIAN[pos])
                    except KeyError:
                        poss.append(k.util.text.laconical(pos, 64))

                sense["poss"] = poss
